version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      GVSjwQoz6KW/yzjpz43ceLENgbyAdq4lD/z4w0cVX5upNRPACg+UcRlrrKXG3L6jOdTrlwKCQ4XmpBw3iaDy2J798VUYH8uelwEF5HMzHcDjO20Wc9rDu9n/Y83qh/hUhgaUQskw6wCGT2unXx7vONvPf2+1kIjNgUI9kmQSrLGzrQK0b01aoVmr5aGzYFzJFrIGOx9fbhkglqr0nPkBcEPjraaPczFi029d7LDgK8+UIrls8hXQG3VyIMdwJPn4KWny2v+VMS4b8n/jEyD1jZiI+IQUJ1ZikUg1wBGpXK59j/a04OhxxNR7r7N5kG0zSHRikVQmGxVURmT0K4b5rwFEdo0dGWB5Yq/HXof8Qm5VVdLG4dSAAtRly6kf41YbfOdWQ10+NpmwCiZ+fNdUwGyiZ+sj0lKuh8DXfcbhPD8rPQkbtDhOVNAIUq3EUcdomqn5sBaN4UMHc18MQBsM+6yulNql9ufztyjZGz+dA8uq3EhS5P+AAfSdgo0wUqyGo5D9A920FoGxtOcMQ4yAG89q46Ni222wLyiK2g+i9R0ajefPc1zvApIpDA1NuYFazy5XajUq97RebuYCCTSiDD0jyy7bud8E1AqS9TiwKmhXZguKECdAFscpsbPFbp3MHMytjFjfITYlS/UaRzscNoTS7I92/NbFFC17j7t9+e8=
