version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      Ku2sN/hYDzHAhClcudIgHTaLz7q+ITGmMVJXWgeTcA1BoPOyhq43uy/MILZPyRCG4qouPaAn2JtjSphKuWACAPS8s7rBUBGjo2P11ZjmNNlAYYDJ2vduTR61LuNqQS9UHUVfYhdxjd4sBdFrZOvrxupidmEPyzBP7SHwatrnp+I/eCGlBRc+XZVXRjBG881sNEw/b81Gob0nFPEgI2B+QogMs8GqzRvPn7iAmDKSuC8KcuJkLkAUSo5YAIc6W6bunhXTf22955tmfy/PmQrfk8fLeRHceIXxthbzTrxDHkyGpvj6fWb9lxzhm/adIp5oZmgW7HiGtNq/U+aTNcerQ4qZ+9pBY0UwqZqnYmiNwr5dARgfG203EMw8Nqy6rrEFXamLt0lm5SaBghcbqIO8VMaJsq5VJlMNVDBIneFztUUGhjuxxf/7SH9UuRp014CWSyubtkQ+IK5Qg9cQyFZEWcwRZqERFpFvK7VMDGp8vSQkK4Mp0NW4lBOVS2ympTDWEq9/OLigBLucE261568qBnsvkP4RZswod7QODPxHXQRh0eAn5uV4T1DUbNproh/vltOzjAdo+/pAaqThmhxoZrCo2FuWUcK7SSEw3PfcZBo5gyJH6r/6J2+LoSwVR6fm0ENb69xCo6d+T0w9GdFkEkl6YOiHF9jSGTMroxdjjvU=
