sudo: false
language: node_js
node_js:
- '8'
- '10'
- '12'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: JKJi11UHnG2cd2e+FCfSTBM8gfhyGSdra/lsx5YgRoZMHrGs1e6Or/+pmPQ/hjNTN4/DAbJGtLgKHCeUfx3zibOPFCuaz5aDcM/MigBkPIISpNdoi7Vt8so6tcnYIBC8DBpeC+AZ+7wPaYIN7h+Z4l0WC2spPqH/fEa9FXFe0Cr2szg9Aj+Ns9jauw75vUTNoKEpU82RCOjMZXU2u04HkLQgsjs2zv3kZqWYt4vgsWO+7nXls8IVr1d55EKPx7nSW6ghhs2Iqebw7JCgF2HAQOF78KDmysVsmvkfplWXux4n2OZyUISS6z2LjAFXUOGrVG8BiFNlPCaRc1oIOHtCpGrFqXeG/phP1MvTZW5zcwJm8q7790jk0YVFX7oDDXw+4Uji1PCXZphYZBk4iQGBi/Kgq6Lr6uiOWsqQmLJC2j/O6M77GTrBAYQP2M4ZxxqCTx4VghX7PtjQNvQI7BkMMtQdyZbI7+rd5KECyBcpVMUVIXSCoJQNMSXnFHOQ2aqYqnI9JEL+KEBSA5YWletsUmZWtwY/1LGhxQ8VT2JuaXxAylMvE9IugVoJVxGfkB3KKIU2FkAb6kG58Fn7BztYnr5hdSO5jNUMB+mVwfC4G5Jid/kxfaImxVZf8/VpQxKr/JDTc6NYRWPHrhc1VndWvNVVNYp1EvNS04JtUiuCN2A=
