version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      cdPpdfrcqeHIT5qUxSmtNM67H2/OB9VInkbG9Lwlc6Da3C/2D8IbEkGe0P2BFJgk4TfNJYbt5auFKN7t6OrKq00wEX9mPVvwwyUlLHi5wLzUtoQfWTPhCypA6slcNpCteF4JCAG6d3bnO3UgKViPzBSumRBhvsv3C3VKCo6IEJY20UgNoVTQzbbNlfFuas9lFF4OM1ouhfRyDDAAwsIVrss4B7+w0ajRRXOVCUgc80p1wBBqeBB7o67fr7Gj5QhEJRFa2lBf1O8zPOWMgPt4Lxw3fKIL4HHFA7XAKw14aRrRArCl8Q6I2eybpQeawVQF2BsYe/VSmt81ho526hVda6+y/Qs1QcUFnwSDPrKsRw2IVctOmD/Dkeo//M48uHQisn4cQ87JtJDrxiNKbdTShqdSXHzEg9We5GgDQSGhaemt5XlQ9vZtve87aiIt3n/9KGBbW1EvhNAoMDqASJuXklFTnbYF4f8q/ETxmpEJ592b947BR24PpOaoC44ZzvH4u7DQRHMMDsk/eQv5/e48qGtApbSbmXLwaXKe1XtD/M9MPy3BKk8IA6nIznUEJYRNcCv0RddIO+qrvX8S3ZkC6M6RIKxpUFH+Jo5HqPSNiJs+JFObCtPUAYSCFUZaAyzn+Vz2lIfF4r+6KH63XfESd3c/CLTPd3uqOyl+SXPM1QE=
