version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      dxDT4OpQ1ae8LfZ+4jxZmqPMRdLuMFC5gtDrN4B2S/rkShYNuDq2iY0MilEB2ZuLvamjC7iGpTq/z5NfUt4ZzdxeHvmKZqmdeZLGRos/0Xp5Whyr7dvLj9nfrm9XBGJN8UbVHjXxECaYejgRcdBBmdl8UWPTjWl0mr3BJSw5kBX0J35J5UVWRB6yY2MbHvcL9T2Ki2Fek8hEm3Am+yECJN+XrRmCVuysrEDKKMSPLsnbDt226OjoZrCzJ4KnwEqXOSQpqPKEY6EU+g2GH3GzuiTcoeFufzbYtUSAXP0oStOw/z4UHdTDbM1hgDP/PKEcj5DFVQe+uHTPTlciv7raW0i7x0JLojpJQQUa1uL0UZVog+UoEr/g/fcKZz488y3SowNLoNuoRDyZoworqD5b8WDbAWUAqWCMdM+CcGa7J3d1MZlSOLRet5HFQOdaBxL6BdaegnZhBE1u4mAfG9OWcF0Y3AbvqPMDyhUYAOI9EEm0Wqc9A7JHcaIHTGucc/uOtzAoaH5EFmdWltW6sc3ThVGqWyV6HD6FGb3FTIzzb8bwVnowZG+0Iwt/XNkIZaW567fH6p+2WmdJEb7lyPMiPJuA+vQ7ok3602ZuhYf3fjJ4b+hN2uVMW1PTPwWsQjN38Qh9k9bIQ8PXzMCl94TJKBd+mPF+Cy7T2LDFuSK6MJs=
