version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      APPP2B4Rjnp10x5Vf+v5vJGTyCo/8nbbTmuDr//4hPMCii5Er1piJu4Nm/WqBeEJxLP+h11NIRU3Iy18a9a7qgNpoh/lO1OUHIpZgaGaVO4HOkY8U/5N9SvMtfVdgxyExipf0Tq39IHI0x2b6sxhhLzo2qnDWofI0R3wvFQD6mQ952PvBQzqfpe2K17FuSPwcpvncANwJ9hyQWdNExuvHnuqb7IqfQuezzb/bmYlgkJsuzG9GXCICJjfU280hXiZQb6uDUD2jeSCQSKReSoDiaflVjiG+VxoYPQwGcwox0ythCUd5ZU3LL5PHm0bwWo7TzS53cS6mUCACrOE678pvx4eqt/MH5a3aEQlfOzatgAH96MWPD1K7nhq+JbwGov9JEUxod98t83qAxiBqibwlcSfjrwUte4A5j+bK8yQFnJ0jYeHQvAiejMIhPkDE6KhCbWGMkSAB+9tBEXBbcS1NcI/1FoAgIA2Q4ainhBnqsoxlERcFDOvvEfy3A/mD5pKV0XRRfVu/V4dtQr+4AWP0hlQjVX+85f1UuTtZvMIFfR0/SR3IaSaAJo/6Zvu9V5PKty3UOR1kiO0HFzPcLy3Z/ttOER0IncXYuh7T+1i75yJuxFz1TlMhw45q5RdXyfljRx4cHR+ivXwOCKu7DzHjvPfz92xAm2GCVeNKMIWoQA=
