version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      nkXJ1oypxh9bISjmhELAVhFfBltZAXJ+nvr7FqDi0cKMQwCe3x8cfYLaidNkXPp4+Lx57XiuYluppXyZJuvI571Ne1gVVg+zqS33w7xz5yZdZ0/mftqHLju9YvRF9PeyliYtmBe/aT87GecfzsF0k+T+uA341K5VR/89TIbVnk1/ClvX7wWyzJD2SG67+XiSuzhKJbY126vF1A6cgTSq9ZvYhLMurZHNqeUSNy46YAmydNFmeMgHZwONTQz+4L41ohU6RxlzeUcpgk1goRUk5G3dgcjr8k2tpyF2U5of9NBbZl8tdLtOrplga18DW+bZnKA+zjKTXtdfV81c9N2eq+T7dOgAdBHkliLmKj0QVr/iJfmip8izeBE3ck65ehdz3HXarKKnfX+atBhpLanriIDd4k8zd4xWj6VQIPN65yes5H+4Hc7VIaaWZ8r3MrQWyoyXhns0qq3CdS6A5GAL0XkglYjB0vJG3MBQPL5aUbZnR3zzOjDcOkQS4GfSt5wEc0MnjPSvo19/dFJGZMFRNcB1D7cQLgsxPV+uZkzHrEFLtcJYAAEmDNeoarYtipvErfr6xnIll9pliBoa/KgTPkgTjgSG8jJHzmnMtTHmGeltOmg7VT9jJc9MbIERh2ScuQOOPOxo+b0Ghen/iYBVCA1iYLYNz6M7iQ7P/CMX/VA=
